[2024-07-17T09:42:00.249+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T09:42:00.283+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_data_dag.parse_data manual__2024-07-17T09:41:56.571487+00:00 [queued]>
[2024-07-17T09:42:00.292+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_data_dag.parse_data manual__2024-07-17T09:41:56.571487+00:00 [queued]>
[2024-07-17T09:42:00.301+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-17T09:42:00.317+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): parse_data> on 2024-07-17 09:41:56.571487+00:00
[2024-07-17T09:42:00.327+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parse_data_dag', 'parse_data', 'manual__2024-07-17T09:41:56.571487+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/parsing_dag.py', '--cfg-path', '/tmp/tmpm7k75fu9']
[2024-07-17T09:42:00.330+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask parse_data
[2024-07-17T09:42:00.335+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T09:42:00.363+0000] {standard_task_runner.py:64} INFO - Started process 86 to run task
[2024-07-17T09:42:00.424+0000] {task_command.py:426} INFO - Running <TaskInstance: parse_data_dag.parse_data manual__2024-07-17T09:41:56.571487+00:00 [running]> on host 1254a1bc6f0b
[2024-07-17T09:42:00.554+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parse_data_dag' AIRFLOW_CTX_TASK_ID='parse_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T09:41:56.571487+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T09:41:56.571487+00:00'
[2024-07-17T09:42:00.556+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T09:42:04.149+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T09:42:04.150+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_dag.py", line 103, in parse_data
    driver.get(f"https://kurs.kz/site/index?city={city}")
                                                  ^^^^
NameError: name 'city' is not defined
[2024-07-17T09:42:04.175+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parse_data_dag, task_id=parse_data, run_id=manual__2024-07-17T09:41:56.571487+00:00, execution_date=20240717T094156, start_date=20240717T094200, end_date=20240717T094204
[2024-07-17T09:42:04.205+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task parse_data (name 'city' is not defined; 86)
[2024-07-17T09:42:04.231+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-17T09:42:04.252+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T09:42:04.255+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
